// scrollable button
export const btnArr = [
  { id: 0, title: "All" },
  { id: 1, title: "Mixes" },
  { id: 2, title: "React.Js" },
  { id: 3, title: "Mern" },
  { id: 4, title: "Music" },
  { id: 5, title: "BPraak" },
  { id: 6, title: "Bollywood" },
  { id: 7, title: "Adhan" },
  { id: 8, title: "Tranding" },
  { id: 9, title: "Live" },
  { id: 10, title: "Song" },
  { id: 11, title: "Comedy" },
  { id: 12, title: "Javascript" },
  { id: 13, title: "Electroni" },
  { id: 14, title: "Watched" },
  { id: 15, title: "Not" },
  { id: 16, title: "Recently" },
  { id: 17, title: "Case" },
  { id: 18, title: "Study" },
  { id: 19, title: "Cook" },
  { id: 20, title: "Studio" },
  { id: 21, title: "Lofi" },
  { id: 22, title: "Tour" },
  { id: 23, title: "Saintmartin" },
  { id: 24, title: "Tech" },
  { id: 25, title: "iPhone" },
  { id: 26, title: "UI" },
  { id: 27, title: "UX" },
  { id: 28, title: "Computer" },
];
// video
export const videoArr = [
  {
    id: 0,
    img_poster: "/assets/m_1.png",
    userImg: "/assets/m_u1.png",
    title1: " A paragraph is a series of sentences that are organized",
    title2: "Lorem ipsum dolor sit amet.",
    title3: "43M views . 2 years ago",
  },
  {
    id: 1,
    img_poster: "/assets/m1.png",
    userImg: "/assets/m_u1.png",
    title1: " A paragraph is a series of sentences that are organized",
    title2: "Lorem ipsum dolor sit amet.",
    title3: "43M views . 2 years ago",
  },
  {
    id: 2,
    img_poster: "/assets/m3.png",
    userImg: "/assets/m_u1.png",
    title1: " A paragraph is a series of sentences that are organized",
    title2: "Lorem ipsum dolor sit amet.",
    title3: "43M views . 2 years ago",
  },
  {
    id: 2,
    img_poster: "/assets/m3.png",
    userImg: "/assets/m_u1.png",
    title1: " A paragraph is a series of sentences that are organized",
    title2: "Lorem ipsum dolor sit amet.",
    title3: "43M views . 2 years ago",
  },
];
// short
export const shortArr = [
  {
    id: 0,
    img_poster: "/assets/s1.png",
    userImg: "",
    title1: " A paragraph is a series of sentences that",
    title2: "",
    title3: "43M views",
  },
  {
    id: 1,
    img_poster: "/assets/s2.png",
    userImg: "",
    title1: " A paragraph is a series of sentences that",
    title2: "",
    title3: "43M views",
  },
  {
    id: 2,
    img_poster: "/assets/s3.png",
    userImg: "",
    title1: " A paragraph is a series of sentences that",
    title2: "",
    title3: "43M views",
  },
  {
    id: 3,
    img_poster: "/assets/s4.png",
    userImg: "",
    title1: " A paragraph is a series of sentences that",
    title2: "",
    title3: "43M views",
  },
];
// breaking news
export const breakNewsArr = [
  {
    id: 0,
    img_poster: "/assets/b1.png",
    userImg: "/assets/m_u1.png",
    title1: " A paragraph is a series of sentences that are organized",
    title2: "Lorem ipsum dolor sit amet.",
    title3: "43M views . 2 years ago",
  },
  {
    id: 1,
    img_poster: "/assets/b2.png",
    userImg: "/assets/m_u1.png",
    title1: " A paragraph is a series of sentences that are organized",
    title2: "Lorem ipsum dolor sit amet.",
    title3: "43M views . 2 years ago",
  },
  {
    id: 2,
    img_poster: "/assets/b1.png",
    userImg: "/assets/m_u1.png",
    title1: " A paragraph is a series of sentences that are organized",
    title2: "Lorem ipsum dolor sit amet.",
    title3: "43M views . 2 years ago",
  },
  {
    id: 3,
    img_poster: "/assets/b2.png",
    userImg: "/assets/m_u1.png",
    title1: " A paragraph is a series of sentences that are organized",
    title2: "Lorem ipsum dolor sit amet.",
    title3: "43M views . 2 years ago",
  },
];
// breaking news
export const infinityArr = [
  {
    id: 0,
    img_poster: "/assets/i1.png",
    userImg: "/assets/m_u1.png",
    title1: " A paragraph is a series of sentences that are organized",
    title2: "Lorem ipsum dolor sit amet.",
    title3: "43M views . 2 years ago",
  },
  {
    id: 1,
    img_poster: "/assets/i2.png",
    userImg: "/assets/m_u1.png",
    title1: " A paragraph is a series of sentences that are organized",
    title2: "Lorem ipsum dolor sit amet.",
    title3: "43M views . 2 years ago",
  },
  {
    id: 2,
    img_poster: "/assets/i3.png",
    userImg: "/assets/m_u1.png",
    title1: " A paragraph is a series of sentences that are organized",
    title2: "Lorem ipsum dolor sit amet.",
    title3: "43M views . 2 years ago",
  },
  {
    id: 2,
    img_poster: "/assets/i3.png",
    userImg: "/assets/m_u1.png",
    title1: " A paragraph is a series of sentences that are organized",
    title2: "Lorem ipsum dolor sit amet.",
    title3: "43M views . 2 years ago",
  },
];
